# Generated by Django 6.0.3 on 2026-04-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
