# Generated by Django 6.0.3 on 2026-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_alter_habit_name_alter_habit_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
